version: '3'

services:
  tree-viewer-postgres:
    build:
      context: ./docker/postgres/
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${PG_PORT}:5432
    container_name: pg_tree_viewer